# Make sure you have following env variables
# when using this Brewfile
#
#  HOMEBREW_CASK_OPTS="--appdir=/Applications"
#  RBENV_ROOT=/usr/local/var/rbenv
#  NVM_DIR=/usr/local/var/nvm

# Essential terminal utilities
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "jonof/kenutils"
tap "heroku/brew"
tap "puma/puma"

brew "advancecomp"
brew "ansible"
brew "autoconf"
brew "curl-openssl"
brew "emojify"
brew "geckodriver"
brew "gifsicle"
brew "git"
brew "gnupg"
brew "pinentry-mac"
brew "graphviz"
brew "heroku"
brew "htop"
brew "httpie"
brew "hub"
brew "imagemagick"
brew "jhead"
brew "jonof/kenutils/pngout"
brew "jpeg"
brew "jpegoptim"
brew "less"
brew "libevent"
brew "libtool"
brew "libyaml"
brew "mackup"
brew "mysql", restart_service: true
brew "optipng"
brew "overmind"
brew "perl"
brew "pngcrush"
brew "pngquant"
brew "postgresql"
brew "qt"
brew "redis", restart_service: true
brew "ssh-copy-id"
brew "terminal-notifier"
brew "tmux"
brew "tree"
brew "vim"
brew "watch"
brew "watchman"
brew "yarn"
brew "z"
brew "zsh"
brew "zsh-completions"
brew "puma-dev"

# Essential Mac applications
# --- BASIC TOOLS ---
cask "alfred"
cask "iterm2"
cask "dropbox"
cask "karabiner-elements"
cask "keka"
cask "keybase"
cask "ngrok"
cask "sequel-pro"
cask "psequel"
cask "resilio-sync"
cask "flux"
# --- FONTS ---
cask "font-fira-code"
cask "font-source-code-pro-for-powerline"
cask "font-hack-nerd-font"
# --- BROWSERS ---
cask "google-chrome"
cask "firefox"
cask "welly"
cask "docker"
# --- Dev TOOLS ---
cask "visual-studio-code"
cask "fork"
cask "imageoptim"
cask "insomnia"
cask "postman"
cask "vagrant"
cask "vagrant-manager"
cask "virtualbox" # something wrong with promission
cask "xquartz"
cask "sketch"
# --- Communication ---
cask "slack"
# --- Applications ---
cask "calibre"           # e-books
cask "sigil"             # e-books
cask "spotify"
cask "subler"
cask "transmission"
cask "geotag-photos-pro"
cask "openemu"
